name:                TodoApp
version:             0.1.0.0
github:              "april-hpxd/haskell-todoapp"
license:             BSD3
author:              "Altynai"
maintainer:          "aruslanova@knox.edu"
extra-source-files:  ["README.md"]

# Library (Task.hs)
library:
  source-dirs: src
  exposed-modules:
    - Task
  dependencies:
    - base >= 4.7 && < 5
    - aeson
    - bytestring
    - directory
    - text
    - containers

# Executable (Main.hs)
executables:
  todoapp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - TodoApp
      - aeson
      - bytestring
      - directory
      - text
      - containers

